#!/bin/sh
#
# This script fixes the library references of this project and makes
#

ROOT="$1"

function log() {
  echo $* >&2
}

function resolve_deps() {
  local lib=$1
  local dep
  otool -L $lib | grep -e "^.$ROOT/" |\
  while read dep _; do
    echo $dep
  done
}

function fix_executable_paths() {
  local lib=$1
  log Fixing $lib
  for dep in `resolve_deps $lib`; do
    local new_dep="@executable_path/..${dep/#$ROOT/}"
    log "|  $dep -> $new_dep"
    install_name_tool -change $dep $new_dep $lib
  done
}

function fix_loader_paths() {
  local lib=$1
  local locallibdir=$ROOT/lib
  log Fixing $lib
  for dep in `resolve_deps $lib`; do
    local new_dep="@loader_path${dep/#$locallibdir/}"
    log "|  $dep -> $new_dep"
    install_name_tool -change $dep $new_dep $lib
  done
}

function fix_pixbuf_loader_paths() {
  local lib=$1
  local locallibdir=$ROOT/lib
  log Fixing $lib
  for dep in `resolve_deps $lib`; do
    local new_dep="@loader_path/../../..${dep/#$locallibdir/}"
    log "|  $dep -> $new_dep"
    install_name_tool -change $dep $new_dep $lib
  done
}

find $ROOT/bin -type f | \
while read f; do
  fix_executable_paths $f
done

find $ROOT/lib -depth 1 -name '*.dylib' | \
while read f; do
  fix_loader_paths $f
done
