name: Build

permissions:
  contents: read

on:
  push:

jobs:

  macos:
    runs-on: macos-15
    permissions:
      contents: write
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Set up workspace
        run: |
          brew install cargo-c gobject-introspection
          brew unlink cairo xz lz4
          python -m venv .venv
          .venv/bin/pip install meson ninja
      - name: Installed homebrew packages
        run: brew list
      - name: meson setup
        run: |
          source .venv/bin/activate
          meson setup --prefix=/opt/adwaita _build
      - name: meson compile
        run: |
          source .venv/bin/activate
          meson install -C _build --destdir $(pwd)/_install
      - name: Make libraries relocatable
        run: |
          cp scripts/make-relocatable "$(pwd)/_install/opt/adwaita"
          cp scripts/post-install "$(pwd)/_install/opt/adwaita"
      - name: Upload Adwaita-Framework
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Adwaita-Framework
          path: _install/
